evanw/node-source-map-support

source-map-support.js
This change allows me to do testing in node of client code using jsdom with proper sourcemap support.
I don't have XMLHttpRequest defined during that time and therefore am not running in the browser.
Thanks.
=> Check XMLHttpRequest is a function for isInBrowser

package.json
Such paths are brittle, due to npm deduping, `mocha` is not guaranteed to be at this location, it may be higher in the tree.
node_modules/.bin is added to the PATH env var for npm scripts so "mocha" on its own is both shorter and will more robustly be able to locate the mocha executable.
Note that is is a problem in the build script as well, for which you could use something like [npm-run](https://www.npmjs.com/package/npm-run)
=> Remove hard-coded path to test executable.

build.js
This uses `path.join` instead of `'/'` and uses npm's convention for running packages in `.bin`.
=> Make build.js cross-platform

source-map-support.js
NodeJS outputs errors to stderr. Making use of console.error(...) instead of console.log(...) makes node-source-map-support compatible with IDEs like Webstorm to get stack traces.
=> Making use of console.error

source-map-support.js
Brutally fixes #57 ... Assuming there is never ' or " within the uri...
=> Fixed sourcemap url detection from code.

package.json
Abstract the build process behind `npm run build`.
It is a good practice as it makes the transition to another build system easier.
=> Add `build` npm script

README.md, register.js
Nicer with ES6:
```javascript
import 'source-map-support/register'
// Instead of:
import sourceMapSupport from 'source-map-support'
sourceMapSupport.install()
```
Source maps support can be enabled on demand directly from the command line for many CLIs:
```
> mocha --require source-map-support/register
```
=> `register` module (fix #52)

README.md, source-map-support.js, test.js
This fixes odd behaviour for source files that contain the literal string
'//# sourceMappingURL=' somewhere in the actual source code.
=> Find the *last* sourceMappingURL in the source document.

source-map-support.js
The newline might look correct in Node's context, but makes `getErrorSource` harder to use in other contexts. This fixes that, while still keeping the existing formatting in `handleUncaughtExceptions`.
=> Remove leading newline in getErrorSource

source-map-support.js
Without this check, missing sourcemaps cause the package to continue as if the 404 message is the sourcemap, leading to crashes when responses like "Not Found" cannot be parsed as source maps.
=> Check for 200 response code.

source-map-support.js
For some reason, some files will have a trailing new line for their
name. This code cleans up the path to no longer have the trailing space.
=> Adding path cleaning

source-map-support.js, test.js
This is the fix first suggested by @nopnop in #65 but slightly modified for code readability and with added test.
> Inline source map prefix should contain an charset:
data:application/json;charset:utf-8;base64,
> This is the case with the last releases of browserify for instance.
This fix make inline source map detection more flexible to support 
this kind of data url (not only with charset) and use a regexp instead
of a static string: /^data:application\/json[^,]+base64,/
> (I didn’t push the generated browser-source-map-support.js with this
PR, do you want me to ?)
=> support charset in data url

source-map-support.js, test.js
This is the fix first suggested by @crispy1989 in #46 but tweaked to work better and have correct tests.
> Node's default behavior is to only print an exception and exit if there is no other uncaughtException handler registered. This emulates that default behavior by bypassing the uncaughtException handler if other handlers are registered.
It also includes #76 so **pull that before** pulling this and this pull request should automatically be updated to only show the one relevant commit.
@evanw @julien-f If you want another maintainer I would be willing to help :)
=> mimic node more closely

source-map-support.js
Fixes #78 
It also includes #76 and #77 so **please pull those before pulling this** and this pull request should automatically be updated to only show the one relevant commit.
=> Check for process object

source-map-support.js, test.js
Change RegExp to be less greedy (Fixes #87). Add test and allow tests to run (and pass) on Windows.
=> Change RegExp to be less greedy (Fixes #87).

source-map-support.js, test.js
This allows for multiple libraries to utilize this without stepping on each other’s toes.
This makes the retrieve helpers additive, giving priority to the last retrieve method registered. In the event of a miss, the next method is called up to and including the default behavior. The `overrideRetriveFile` and `overrideRetrieveSourceMap` flags are added if this behavior is not desired but this is something that most libraries should avoid to be good citizens.
Flagged behaviors will now be on if any of the install calls dictate that they would be.
Fix for #91
=> Allow for multiple install calls

source-map-support.js, test.js
Trying to wrap a `CallSite` that is native leads to unexpected behaviour. In a particular case that I had, the lib tries to make a `XMLHttpRequest` for a file called `native array.js`, which doesn't actually exist.
I couldn't figure out the root cause, but this is the way I found to address it, and it resolved the problem fully without causing side effects.
=> return native code CallSite as is

source-map-support.js
When using Electron with `nodeIntegration` enabled, it's better to use native filesystem logic, rather than XHR. This adds detection for that.
=> Use 'node' version when using Electron with nodeIntegration enabled

README.md
So you actually don't need to use import 'source-map-support/register'
=> Document that babel-register already uses source-map-support

README.md, source-map-support.js, test.js
Adds the hookRequire option which monkey patches _compile to support require extension hooks that use inline source maps. This is necessary because the default retrieveFile implementations point to the original source file when doing runtime transpilation and thus don’t have the source map attached.
=> Add support for runtime inline source maps

source-map-support.js, test.js
The toString shim does not print the typeName for CallSite, in node 4 and below the same as the native toString method.
Found this while running the node-tap test suite to add source map support into the stack traces of node-tap
tapjs/node-tap#329
File: t.js
```
setTimeout(function () {
throw { stack: new Error('this one').stack }
})
setTimeout(function () {
throw new Error('not this one')
}, 100)
```
File t.js - With Source Map Support
```
require('./source-map-support').install();
setTimeout(function () {
throw { stack: new Error('this one').stack }
})
setTimeout(function () {
throw new Error('not this one')
}, 100)
```
```
[node-source-map-support[master ?*]]-> nvm use 0
Now using node v0.12.16 (npm v2.15.1)
[node-source-map-support[master ?*]]-> node t.js …
```
=> Fix toString shim to be backwards compatible with node v4 and below 

package.json
The issue in #164 is that the browser js version wasn't updated with the changes much needed in 0.6.4.
Be good to automate this before publishing the package.
=> Run build.js before publishing

source-map-support.js
A reason is from https://github.com/Jam3/devtool/issues/74, and recently [babel-register is updated source-map-support to ^0.4.2](https://github.com/babel/babel/commit/90f3f9049f05090343ffeb10bbc2634096bfd1c0), the `sourceMappingURL=foo.js.map` comment will broken babel-register on [Jam3/devtool](https://github.com/Jam3/devtool).
=> Remove sourceMappingURL comment

.gitignore, build.js, package.json, source-map-support.js, test.js, webpack-test/index.html, webpack-test/script.js, webpack-test/webpack.config.js
This converts the webpack errors to warnings. Individual users may use the ignore plugin to further mute these warnings.
=> Fix webpack support

source-map-support.js
Fixes https://github.com/evanw/node-source-map-support/issues/167
Since version 0.4.9, we require `fs` but it should fail if we are in
a browser. However, `browser-source-map-support.js` is bundled with
browserify which converts unsupported builtins to empty object. See
https://github.com/substack/node-browserify/blob/8f5ebbf505/lib/builtins.js#L12
This PR checks if required `fs` contains `readFileSync` which is part
of `fs` API.
Tests:
```
npm run build && npm run serve-tests
```
Then open http://127.0.0.1:1336/browser-test/
=> Fix Uncaught Type Error

test.js
All 28 Mocha tests were failing, and now pass.
Resolves Issue #89, and updates the stale PR #90.
=> Update tests for Windows `\r\n` newline and `\` path delimeter

package.json
Updates source-map to v0.5.6 to resolve issue #141.
Tests still pass, except the known problem with browserify (PR #66).
=> Issue 141: Bumping source-map to latest

source-map-support.js
instead of return null, keep looking for sourcemap
=> fix: browser regression from #169 when getResponseHeader throws

.npmignore
The compiled output of the webpack test is about 468k on disk. It looks like its inclusion in the package was an oversight, so I figured it couldn't hurt to try to remove it.
=> Added webpack-test to .npmignore

README.md
The previous link was leading nowhere. The docs are now hosted on https://github.com/v8/v8/wiki.
=> Updates link in README to V8 Stack Trace API

source-map-support.js
There may be errors on line 1 column 1 and those resulted in a column of -62 which threw an out-of-range error.
Our example was: "v8debug is not defined" which can occur when debugging a node app from WebStorm
=> Defensive coding to prevent out-of-range column

.npmignore
As far as I can see, the following files are not needed to run the package:
- .npmignore
- .travis.yml
- build.js
- test.js
=> Cleanup npm package

source-map-support.js, test.js
Generating a call stack when using this library can trigger a call to
fs.readFileSync.  That call can sometimes fail, resulting in a very
confusing stack trace (or none at all, which is even more confusing).
This patch wraps calls to fs.readFileSync() in a try/catch.  If the read
fails, then the file contents are omitted, but this is far better than
total failure.
Tracking down this one was fun, as you can probably imagine :)
=> Be resilient against readFileSync failures

README.md
=> Add note about -r when using with node

source-map-support.js
Trying to debug node with DevTools with transpiled code on Windows is a mess. First, this is *not* the fault of node-source-map-support at all. It works great on windows on its own. But the hacks necessary to get this to work do break node-source-map-support.
The basic problem is this: Node uses OS file paths, and DevTools doesn't understand OS file paths, it only understands URIs (including file:// URIs). So to actually get DevTools to comprehend source maps (so that you can set breakpoints and step through source code), you need to map your node modules to file:// URIs, so that DevTools can then do the relative path lookups to find your source maps/code. This means your modules that registered in Node need to have filenames like "file:///C:/dev/my-module.js". And this is where the most …
=> Add support for proper handling of file protocol (in windows)

source-map-support.js
It turns out the last PR didn't quite solve file:// protocol handling in *nix systems, as there some tricky differences between file URLs on windows and unix. In particular, a windows URL like "file:///C:/dir/file" needs to be stripped of all three slashes to "C:/dir/file", but a unix URL like "file:///root-dir/file" needs to be stripped of two slashes to "/dir/file". The easy solution would be to use node's `URL` constructor, and pass the `URL` instance to `existsSync`/`readFileSync`, but that is not supported on older node versions, which I think this project is committed to supporting. The solution I provided isn't pretty, but seem to work across both styles of file URLs, and is a relatively minor change.
This issue on unix is as problematic as on windows. At least in unix, dev tools …
=> Fix handling of file:/// paths on *nix systems

source-map-support.js
Calling `process.exit(1)` exits the process immediately and might prevent writes from completing as explained in [process.exit documentation](https://nodejs.org/api/process.html#process_process_exit_code). Setting the `exitCode` property instead lets pending events in the event loop run (like writing to stderr) but prevents any additional work from being scheduled. This is the recommended way to exit Node processes.
=> Fixes #207: Synchronously log error on exit

source-map-support.js
I haven't added docs as I don't think this is the correct way to do this...
Background:
Jest has a CLI flag called `--detectLeaks` which tries to sniff out memory leaks in your test suite.
We discovered today that Jest itself seems to be leaking, and bisected it to https://github.com/facebook/jest/commit/3341d162715679a596bfbbec8a7a5c5676c5f1b7. After fiddling a bit with it, I discovered that if I remove the whole `retrieveSourceMap` function from the options passed to `install`, it doesn't complain about a leak. Just making the function be empty and always return `null` still reported a leak.
The only way I was able to find that lets us keep using `retrieveSourceMap` but not leak was to add the function added in this PR.
It feels really hacky, so I'd love to find a way forward without …
=> Add `resetRetrieveHandlers` to avoid memory leak

source-map-support.js
This is based on my comment in PR #208 which caused exceptions not to be printed to the console when debugging (eg. using Chromium or VS Code). I've also simplified the code a bit.
=> Fix exception not printed when debugging

source-map-support.js, test.js
Continuing #205 
The tests were failing due to not falling back to the original name when the source map position did not have a name.
=> use original name from source in error trace

source-map-support.js
When the XHR request throws an error (e.g. in case of CORS issues), it is now catched properly. Needed to fix weird Karma/Jasmine issues in Angular CLI projects.
Closes https://github.com/angular/angular-cli/issues/7296.
=> Catch XHR errors

source-map-support.js
Hardens the structural typecheck performed in `mapSourcePosition` before executing `originalPositionFor` methods on `sourceMap.map` objects. 
This addresses a bug I encountered with `electron-updater` while working on https://github.com/meetalva/alva/, where `Promise` values somehow end up in `sourceMap.map`, causing the app to crash with stack traces like this.
```
-/app.asar/node_modules/source-map-support/source-map-support.js:214
var originalPosition = sourceMap.map.originalPositionFor(position);
^
TypeError: sourceMap.map.originalPositionFor is not a function
at mapSourcePosition (-/app.asar/node_modules/source-map-support/source-map-support.js:214:42)
at wrapCallSite (-/app.asar/node_modules/source-map-support/source-map-support.js:358:20)
at …
```
=> Check if .map.originalPositionFor is a function before executing

source-map-support.js
The `handlerExec` function produces functions that are using original `retrieveFileHandlers`/`retrieveMapHandlers` references, so because the array variables are  re-assigned in the `resetRetrieveHandlers` function, `retrieveSourceMap` and `retrieveFile` need to be re-created to point them to correct instances of `retrieveFileHandlers`/`retrieveMapHandlers`.
This fixes:
https://github.com/facebook/jest/issues/6424
https://github.com/facebook/jest/issues/7402
=> Fix `resetRetrieveHandlers` to reset `retrieveSourceMap` and `retrieveFile` functions

source-map-support.js, test.js
`console.trace` sends an object with `name` and `message` instead of an `Error`,
thus rendering the function unusable due to erroneous message output of
`"[object Object]"`. This fixes #195
=> Fix: formatting in prepareStackTrace when error isn't of instance Error

source-map-support.js, test.js
This is a follow-up to #220.
In #220 we provided `position.name` before `stack.getFunctionName` to support mangled function calls. However, `stack.getFunctionName` is supposed to return the name of the _current_ function, that is, which function does this frame live in. Regards to the source map, it is the `name` of the position in _next_ frame instead of in this frame.
To illustrate this issue, here is a reproducible [repository](https://github.com/JLHwung/source-map-support-bug) I revised from https://github.com/babel/babel/issues/9883:
```js
function foo() {
console.log(new Error().stack);
}
function bar() {
foo();    // <-- Here we are supposed to get `bar` as function name but instead get `foo`.
}
bar();
```
The expected output should be
```log
at foo …
```
=> fix: function name should be obtained from next frame’s position

source-map-support.js, test.js
As of version 11.11.0 (and backported to 10.16), node automatically strips
the module closure header from the module source code.  So, the fix for that
caused off-by-one errors in the sourcemapped file.
=> fix: Adapt to node's removal of the module header

source-map-support.js
Node.js Worker threads don’t handle `uncaughtException` the same way
that the main thread does. The shim does not apply/make sense here,
but breaks error handling support in unexpected ways instead.
Fixes: https://github.com/evanw/node-source-map-support/issues/268
Fixes: https://github.com/TypeStrong/ts-node/issues/945
=> Fix Node.js Worker support by not shimming uncaughtException

source-map-support.js
Fixes #270 
We might want to use this for `fs` as well 🤔
=> Fix WebPack compatibility by using dynamic require

register-hook-require.js
Provide a `source-map-support/register-hook-require` entry-point (fixes #239)
=> `register-hook-require` entry point

README.md
=> add info about node 12.12.0 `--enable-source-maps`
